#!/usr/bin/env escript
%% -*- erlang -*-
%%% @author Tony Rogvall <tony@rogvall.se>
%%% @copyright (C) 2013, Tony Rogvall
%%% @doc
%%%    varp command line interface
%%% @end
%%% Created : 27 Nov 2013 by Tony Rogvall <tony@rogvall.se>



	    
 
