start: definitions
| definitions lexpr
| lexpr

definitions: definition+

?definition: "define" pexpr lexpr ";" -> define
| "declare" pdecls ";"  -> declare
| "literals" ldecls ";" -> literals
| "order" odecls ";" -> order
| "assert" expr ";" -> assert
| "input" IDENTIFIER ";" -> input
| "output" IDENTIFIER ";" -> output

?primary_expr: IDENTIFIER
| constant
| "(" expr ")"
| "{" expr "}" -> vec

?postfix_expr:  primary_expr
| postfix_expr "[" expr "]" -> index
| postfix_expr "(" ")" -> call
| postfix_expr "(" argument_expr_list ")" -> call
| postfix_expr "." IDENTIFIER -> field
| postfix_expr "->" IDENTIFIER -> pointer

?argument_expr_list: assignment_expr
	    | argument_expr_list "," assignment_expr

?unary_expr: postfix_expr
	| unary_operator unary_expr

unary_operator:  "+" | "-" | "~"

?multiplicative_expr: unary_expr
| multiplicative_expr "*" unary_expr -> mult
| multiplicative_expr "/" unary_expr -> div
| multiplicative_expr "%" unary_expr -> rem

?additive_expr: multiplicative_expr
| additive_expr "+" multiplicative_expr -> add
| additive_expr "-" multiplicative_expr -> sub

?shift_expr: additive_expr
| shift_expr "<<" additive_expr -> shl
| shift_expr ">>" additive_expr -> shr

?relational_expr: shift_expr
| relational_expr "<" shift_expr  -> lt
| relational_expr ">" shift_expr  -> gt
| relational_expr "<=" shift_expr -> lte
| relational_expr ">=" shift_expr -> gte

?equality_expr: relational_expr
| equality_expr "==" relational_expr -> eq
| equality_expr "!=" relational_expr -> neq

?and_expr: equality_expr
| and_expr "&" equality_expr -> band

?exclusive_or_expr: and_expr
| exclusive_or_expr "^" and_expr -> bxor

?inclusive_or_expr: exclusive_or_expr
|  inclusive_or_expr "|" exclusive_or_expr -> bor

?logical_and_expr: inclusive_or_expr
| logical_and_expr "&&" inclusive_or_expr -> and

?logical_or_expr: logical_and_expr
|  logical_or_expr "||" logical_and_expr -> or

?conditional_expr: logical_or_expr
| logical_or_expr "?" logical_or_expr ":" conditional_expr -> cond

?assignment_expr: conditional_expr
|  conditional_expr ".." conditional_expr -> range
|  unary_expr "=" assignment_expr -> assign

?expr: assignment_expr ("," assignment_expr)*

?constant: HEXNUM
| OCTNUM
| DECNUM
| BINNUM

?integer: BINNUM
| OCTNUM
| DECNUM
| HEXNUM

?qtype: "E!" -> one
| "E"      -> any
| "A"      -> all
| "ALL"    -> all
| "ANY"    -> any
| "ONE"    -> one
| "NONE"   -> none
| "EQ"     -> eq
| "NEQ"    -> neq
| "GT"     -> gt
| "GTE"    -> gte
| "LT"     -> lt
| "LTE"    -> lte
| "SUM"    -> sum
| "PROD"   -> prod
| "PARITY" -> parity
| "ODD"    -> odd
| "EVEN"   -> even

quantifier: "[" "ALL" "]"  -> all
| "[" "ANY" "]"  -> any
| "[" "NONE" "]" -> none
| "[" "ONE"  "]" -> one
| "[" "SUM" "]"  -> sum
| "[" "PROD" "]" -> prod
| "[" "PARITY" "]" -> parity
| "[" "ODD" "]"    -> odd
| "[" "EVEN" "]"   -> even
| "[" "E" "]"      -> any
| "[" "E!" "]"     -> one
| "[" "A" "]"      -> all
| "[" qtype expr "]" -> quant

// Declaration of integers (can be extended)
?pdecl: pexpr ":" sexpr "/signed" -> signed
| pexpr ":" sexpr "/unsigned" -> unsigned
| pexpr ":" sexpr -> unsigned

?pdecls: pdecl ("," pdecl)*

?ldecls: ldecl ("," ldecl)*

?ldecl: IDENTIFIER

?odecls: odecl ("," odecl)*

?odecl: "rank" -> rank
| "+rank" -> p_rank
| "-rank" -> n_rank
| "degree" -> degree
| "+degree" -> p_degree
| "-degree" -> n_degree
| "random" -> random
| "+random" -> p_random
| "-random" -> n_random
| "identity" -> identity
| "+identity" -> p_identity
| "-identity" -> n_identity
| "user" -> user
| "+user" -> p_user
| "-user" -> n_user
| oexpr 

// bit collection
?oexpr: pexpr
| pexpr "[" expr "]" -> bitindex
| pexpr "[" expr ":" expr "]" -> bitrange
| pexpr "[" expr ":" expr ":" expr "]" -> bitrange
| pexpr ":" sexpr "/" "signed"  -> signed
| pexpr ":" sexpr "/" "unsigned" -> unsigned
|  "!" pexpr

// Logic expression
?lexpr_var: pexpr
| pcexpr ":" sexpr "/signed" -> signed
| pcexpr ":" sexpr "/unsigned" -> unsigned
| pcexpr ":" sexpr -> unsigned

?lexpr_const: integer | IDENTIFIER

?lexpr0: "true" -> true
|  "false" -> false
|  lexpr_var
|  lexpr_const
|  "-" lexpr0  -> neg
|  "not" lexpr0 -> not
|  "!" lexpr0 -> not
|  "~" lexpr0 -> bnot
|  "(" lexpr ")"
|  "{" lexprs "}" -> vec
|  IDENTIFIER "(" lexprs ")" -> mcall
|  quantifier "(" lexprs ")"
|  quantifier lexpr0
|  lexpr0 "[" expr "]" -> bitindex
|  lexpr0 "[" expr ":" expr "]" -> bitrange
|  lexpr0 "[" expr ":" expr ":" expr "]" -> bitrange


?lexpr10: lexpr0
|  lexpr10 "*" lexpr0
| lexpr10 "/" lexpr0
| lexpr10 "%" lexpr0

?lexpr20: lexpr10
| lexpr20 "+" lexpr10  -> add
| lexpr20 "-" lexpr10  -> sub

?lexpr30: lexpr20
| lexpr30 "<<" lexpr20  -> shl
| lexpr30 ">>" lexpr20  -> shr
| lexpr30 "<<<" lexpr20 -> rshl
| lexpr30 ">>>" lexpr20 -> rshr

?lexpr40: lexpr30
| lexpr40 "<"  lexpr30  -> less
| lexpr40 "<=" lexpr30  -> less_equal
| lexpr40 ">"  lexpr30  -> greater
| lexpr40 ">=" lexpr30  -> greter_equal

?lexpr41: lexpr40
| lexpr41 "==" lexpr40  -> equal
| lexpr41 ":=" lexpr40  -> alias
| lexpr41 "!=" lexpr40  -> not_equal

?lexpr43: lexpr41
| lexpr43 "&" lexpr41 -> band

?lexpr45: lexpr43
| lexpr45 "^" lexpr43 -> bxor

?lexpr47: lexpr45
| lexpr47 "|" lexpr45

?lexpr50: lexpr47
| lexpr50 "and" lexpr47 -> and
| lexpr50 "&&"  lexpr47 -> and

?lexpr60: lexpr50
| lexpr60 "xor" lexpr50 -> xor

?lexpr70: lexpr60
| lexpr70 "or"  lexpr60 -> or
| lexpr70 "||"  lexpr60 -> or

?lexpr80: lexpr70
| lexpr80 "->"  lexpr70 -> imp
| lexpr80 "imp" lexpr70 -> imp
| lexpr80 "implies" lexpr70 -> imp

?lexpr90: lexpr80
| lexpr90 "equ" lexpr80 -> equ
| lexpr90 "equivalent" lexpr80 -> equ
| lexpr90 "<->" lexpr80 -> equ

?lexpr: lexpr90

?lexprs: lexpr ("," lexpr)*

?sexpr: "(" expr ")"
| integer
| "char"
| "short"
| "long"
| "int"
| IDENTIFIER

?pexpr: SYMBOL
| SYMBOL "(" ")"
| SYMBOL "(" expr ")" -> symbol

?pcexpr: pexpr | integer | IDENTIFIER

IDENTIFIER: LETTER (LETTER|DIGIT)*
SYMBOL.2: UCASE_LETTER (UCASE_LETTER|DIGIT)*

HEXNUM: "0"("x"|"X") HEXDIGIT+
BINNUM: "0"("b"|"B") ("0"|"1")+
OCTNUM: "0" DIGIT+
DECNUM: DIGIT+

COMMENT: "//" /[^\n]/*  // line comment

%import common.DIGIT
%import common.HEXDIGIT
%import common.LETTER
%import common.UCASE_LETTER
%import common.WS

%ignore WS
%ignore COMMENT
