#
# Make the python/nif wrapper for varc.so
#
# make -f Makefile.varpy
#
CC = gcc
CFLAGS = -fPIC -I/usr/include/python2.7 -shared
PYNAME = varp

varp.so: $(HOME)/erlang/pynif/c_src/pynif.c
	$(CC) $(CFLAGS) -o varp.so -DPYNIFNAME=$(PYNAME) varc_nif.o $<
