#
# Makefile for Mingw
#
OSNAME := $(shell uname -s)
MACHINE := $(shell uname -m)
ERLDIR	:= $(shell erl -noshell -eval "io:format([126,115,126,110],[code:root_dir()])" -s erlang halt)
ERL_C_INCLUDE_DIR := "$(ERLDIR)/usr/include"
CC = gcc
PRIVDIR=../priv

CFLAGS += -D__WIN32__ -DWIN32 -D_MT -D_DLL -DEBUG_MEM -DDLOG_DEFAULT=DLOG_NONE
CFLAGS += -Wall -Wextra -Wswitch-default -Wswitch-enum -D_THREAD_SAFE -D_REENTRANT -fno-common
CFLAGS += -I$(ERL_C_INCLUDE_DIR)
#LDFLAGS += -Wl--enable-stdcall-fixup

EXT = dll
LD_SHARED	:= $(CC) -shared

debug: CFLAGS += -g
debug: LDFLAGS += -g

VARP_NIF = $(PRIVDIR)/varc_nif.$(EXT)


VARP_NIF_OBJS = varc_nif.obj

debug release all: $(VARP_NIF)

$(VARP_NIF): $(VARP_NIF_OBJS) 
	$(LD_SHARED) -o $@ $(VARP_NIF_OBJS) $(LDFLAGS)

%.obj: %.c
	$(CC) -c -o $@ $(CFLAGS) $<
