#
# Make the python/nif wrapper for varc.so
#
# make -f Makefile.varpy
#

# PYTHON = python2.7
PYTHON = python3

PYTHON_CFLAGS = $(shell $(PYTHON)-config --cflags)
PYTHON_LDFLAGS = $(shell $(PYTHON)-config --ldflags)

ERLDIR	:= $(shell erl -noshell -eval "io:format([126,115,126,110],[code:root_dir()])" -s erlang halt)
NIF_CFLAGS = -fPIC -I"$(ERLDIR)/usr/include" -O2 -Wall

CC = gcc
CFLAGS = -fPIC $(PYTHON_CFLAGS) -Wno-unused-parameter # -Wextra

LD_SHARED = $(CC) -shared

PYNAME = varp

../py/varp.so: ../py/pynif.o ../py/varc_nif.o
	 $(LD_SHARED) -o $@ ../py/varc_nif.o ../py/pynif.o

../py/pynif.o: pynif.c
	 $(CC) -c -o $@ -DPYNIFNAME=$(PYNAME) $(CFLAGS) $<

../py/varc_nif.o: varc_nif.c
	$(CC) -c -o $@ -DPYNIF $(NIF_CFLAGS) $<
