-file("/usr/local/lib/erlang/lib/parsetools-2.0.7/include/leexinc.hrl", 0).
%% The source of this file is part of leex distribution, as such it
%% has the same Copyright as the other files in the leex
%% distribution. The Copyright is defined in the accompanying file
%% COPYRIGHT. However, the resultant scanner generated by leex is the
%% property of the creator of the scanner and is not covered by that
%% Copyright.

-module(varp_scan).

-export([string/1,string/2,token/2,token/3,tokens/2,tokens/3]).
-export([format_error/1]).

%% User code. This is placed here to allow extra attributes.
-file("./varp_scan.xrl", 101).


-file("/usr/local/lib/erlang/lib/parsetools-2.0.7/include/leexinc.hrl", 14).

format_error({illegal,S}) -> ["illegal characters ",io_lib:write_string(S)];
format_error({user,S}) -> S.

string(String) -> string(String, 1).

string(String, Line) -> string(String, Line, String, []).

%% string(InChars, Line, TokenChars, Tokens) ->
%% {ok,Tokens,Line} | {error,ErrorInfo,Line}.
%% Note the line number going into yystate, L0, is line of token
%% start while line number returned is line of token end. We want line
%% of token start.

string([], L, [], Ts) ->                     % No partial tokens!
    {ok,yyrev(Ts),L};
string(Ics0, L0, Tcs, Ts) ->
    case yystate(yystate(), Ics0, L0, 0, reject, 0) of
        {A,Alen,Ics1,L1} ->                  % Accepting end state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {A,Alen,Ics1,L1,_S1} ->              % Accepting transistion state
            string_cont(Ics1, L1, yyaction(A, Alen, Tcs, L0), Ts);
        {reject,_Alen,Tlen,_Ics1,L1,_S1} ->  % After a non-accepting state
            {error,{L0,?MODULE,{illegal,yypre(Tcs, Tlen+1)}},L1};
        {A,Alen,_Tlen,_Ics1,L1,_S1} ->
            string_cont(yysuf(Tcs, Alen), L1, yyaction(A, Alen, Tcs, L0), Ts)
    end.

%% string_cont(RestChars, Line, Token, Tokens)
%% Test for and remove the end token wrapper. Push back characters
%% are prepended to RestChars.

string_cont(Rest, Line, {token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, {end_token,T}, Ts) ->
    string(Rest, Line, Rest, [T|Ts]);
string_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, [T|Ts]);
string_cont(Rest, Line, skip_token, Ts) ->
    string(Rest, Line, Rest, Ts);
string_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    string(NewRest, Line, NewRest, Ts);
string_cont(_Rest, Line, {error,S}, _Ts) ->
    {error,{Line,?MODULE,{user,S}},Line}.

%% token(Continuation, Chars) ->
%% token(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {token,State,CurrLine,TokenChars,TokenLen,TokenLine,AccAction,AccLen}

token(Cont, Chars) -> token(Cont, Chars, 1).

token([], Chars, Line) ->
    token(yystate(), Chars, Line, Chars, 0, Line, reject, 0);
token({token,State,Line,Tcs,Tlen,Tline,Action,Alen}, Chars, _) ->
    token(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Action, Alen).

%% token(State, InChars, Line, TokenChars, TokenLen, TokenLine,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% The argument order is chosen to be more efficient.

token(S0, Ics0, L0, Tcs, Tlen0, Tline, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{token,S1,L1,Tcs,Alen1,Tline,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            token_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline));
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{token,S1,L1,Tcs,Tlen1,Tline,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     true -> {eof,L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,Ics1,L1,_S1} ->    % No token match
            Error = {Tline,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            {done,{error,Error,L1},Ics1};
        {A1,Alen1,_Tlen1,_Ics1,L1,_S1} ->       % Use last accept match
            token_cont(yysuf(Tcs, Alen1), L1, yyaction(A1, Alen1, Tcs, Tline))
    end.

%% token_cont(RestChars, Line, Token)
%% If we have a token or error then return done, else if we have a
%% skip_token then continue.

token_cont(Rest, Line, {token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, {end_token,T}) ->
    {done,{ok,T,Line},Rest};
token_cont(Rest, Line, {end_token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,Line},NewRest};
token_cont(Rest, Line, skip_token) ->
    token(yystate(), Rest, Line, Rest, 0, Line, reject, 0);
token_cont(Rest, Line, {skip_token,Push}) ->
    NewRest = Push ++ Rest,
    token(yystate(), NewRest, Line, NewRest, 0, Line, reject, 0);
token_cont(Rest, Line, {error,S}) ->
    {done,{error,{Line,?MODULE,{user,S}},Line},Rest}.

%% tokens(Continuation, Chars, Line) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Tokens,AccAction,AccLen}
%% {skip_tokens,State,CurrLine,TokenChars,TokenLen,TokenLine,Error,AccAction,AccLen}

tokens(Cont, Chars) -> tokens(Cont, Chars, 1).

tokens([], Chars, Line) ->
    tokens(yystate(), Chars, Line, Chars, 0, Line, [], reject, 0);
tokens({tokens,State,Line,Tcs,Tlen,Tline,Ts,Action,Alen}, Chars, _) ->
    tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Ts, Action, Alen);
tokens({skip_tokens,State,Line,Tcs,Tlen,Tline,Error,Action,Alen}, Chars, _) ->
    skip_tokens(State, Chars, Line, Tcs ++ Chars, Tlen, Tline, Error, Action, Alen).

%% tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Ts, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1} ->
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,S1} ->                  % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Alen1,Tline,Ts,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->               % Take what we got
            tokens_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Ts);
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,S1} ->            % Need more chars to check
            {more,{tokens,S1,L1,Tcs,Tlen1,Tline,Ts,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,_S1} ->     % No token match
            %% Check for partial token which is error, no need to skip here.
            Ret = if Tlen1 > 0 -> {error,{Tline,?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},L1};
                     Ts == [] -> {eof,L1};
                     true -> {ok,yyrev(Ts),L1}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            %% Skip rest of tokens.
            Error = {L1,?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,_Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            tokens_cont(yysuf(Tcs, Alen1), L1, Token, Ts)
    end.

%% tokens_cont(RestChars, Line, Token, Tokens)
%% If we have an end_token or error then return done, else if we have
%% a token then save it and continue, else if we have a skip_token
%% just continue.

tokens_cont(Rest, Line, {token,T}, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, [T|Ts], reject, 0);
tokens_cont(Rest, Line, {end_token,T}, Ts) ->
    {done,{ok,yyrev(Ts, [T]),Line},Rest};
tokens_cont(Rest, Line, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    {done,{ok,yyrev(Ts, [T]),Line},NewRest};
tokens_cont(Rest, Line, skip_token, Ts) ->
    tokens(yystate(), Rest, Line, Rest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, NewRest, 0, Line, Ts, reject, 0);
tokens_cont(Rest, Line, {error,S}, _Ts) ->
    skip_tokens(Rest, Line, {Line,?MODULE,{user,S}}).

%%skip_tokens(InChars, Line, Error) -> {done,{error,Error,Line},Ics}.
%% Skip tokens until an end token, junk everything and return the error.

skip_tokens(Ics, Line, Error) ->
    skip_tokens(yystate(), Ics, Line, Ics, 0, Line, Error, reject, 0).

%% skip_tokens(State, InChars, Line, TokenChars, TokenLen, TokenLine, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

skip_tokens(S0, Ics0, L0, Tcs, Tlen0, Tline, Error, A0, Alen0) ->
    case yystate(S0, Ics0, L0, Tlen0, A0, Alen0) of
        {A1,Alen1,Ics1,L1} ->                  % Accepting end state
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,[],L1,S1} ->                 % After an accepting state
            {more,{skip_tokens,S1,L1,Tcs,Alen1,Tline,Error,A1,Alen1}};
        {A1,Alen1,Ics1,L1,_S1} ->
            skip_cont(Ics1, L1, yyaction(A1, Alen1, Tcs, Tline), Error);
        {A1,Alen1,Tlen1,[],L1,S1} ->           % After a non-accepting state
            {more,{skip_tokens,S1,L1,Tcs,Tlen1,Tline,Error,A1,Alen1}};
        {reject,_Alen1,_Tlen1,eof,L1,_S1} ->
            {done,{error,Error,L1},eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,_S1} ->
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, Error);
        {A1,Alen1,_Tlen1,_Ics1,L1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline),
            skip_cont(yysuf(Tcs, Alen1), L1, Token, Error)
    end.

%% skip_cont(RestChars, Line, Token, Error)
%% Skip tokens until we have an end_token or error then return done
%% with the original rror.

skip_cont(Rest, Line, {token,_T}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {end_token,_T}, Error) ->
    {done,{error,Error,Line},Rest};
skip_cont(Rest, Line, {end_token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    {done,{error,Error,Line},NewRest};
skip_cont(Rest, Line, skip_token, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {skip_token,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, NewRest, 0, Line, Error, reject, 0);
skip_cont(Rest, Line, {error,_S}, Error) ->
    skip_tokens(yystate(), Rest, Line, Rest, 0, Line, Error, reject, 0).

yyrev(List) -> lists:reverse(List).
yyrev(List, Tail) -> lists:reverse(List, Tail).
yypre(List, N) -> lists:sublist(List, N).
yysuf(List, N) -> lists:nthtail(N, List).

%% yystate() -> InitialState.
%% yystate(State, InChars, Line, CurrTokLen, AcceptAction, AcceptLen) ->
%% {Action, AcceptLen, RestChars, Line} |
%% {Action, AcceptLen, RestChars, Line, State} |
%% {reject, AcceptLen, CurrTokLen, RestChars, Line, State} |
%% {Action, AcceptLen, CurrTokLen, RestChars, Line, State}.
%% Generated state transition functions. The non-accepting end state
%% return signal either an unrecognised character or end of current
%% input.

-file("varp_scan.erl", 277).
yystate() -> 45.

yystate(81, [124|Ics], Line, Tlen, _, _) ->
    yystate(46, Ics, Line, Tlen+1, 18, Tlen);
yystate(81, Ics, Line, Tlen, _, _) ->
    {18,Tlen,Ics,Line,81};
yystate(80, [114|Ics], Line, Tlen, _, _) ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(80, [95|Ics], Line, Tlen, _, _) ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(80, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(80, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(80, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 113 ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(80, [C|Ics], Line, Tlen, _, _) when C >= 115, C =< 122 ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(80, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line,80};
yystate(79, [100|Ics], Line, Tlen, _, _) ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(79, [95|Ics], Line, Tlen, _, _) ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(79, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(79, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(79, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 99 ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(79, [C|Ics], Line, Tlen, _, _) when C >= 101, C =< 122 ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(79, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line,79};
yystate(78, [95|Ics], Line, Tlen, _, _) ->
    yystate(37, Ics, Line, Tlen+1, 2, Tlen);
yystate(78, [77|Ics], Line, Tlen, _, _) ->
    yystate(49, Ics, Line, Tlen+1, 2, Tlen);
yystate(78, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(37, Ics, Line, Tlen+1, 2, Tlen);
yystate(78, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 76 ->
    yystate(37, Ics, Line, Tlen+1, 2, Tlen);
yystate(78, [C|Ics], Line, Tlen, _, _) when C >= 78, C =< 90 ->
    yystate(37, Ics, Line, Tlen+1, 2, Tlen);
yystate(78, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(37, Ics, Line, Tlen+1, 2, Tlen);
yystate(78, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line,78};
yystate(77, [95|Ics], Line, Tlen, _, _) ->
    yystate(37, Ics, Line, Tlen+1, 2, Tlen);
yystate(77, [78|Ics], Line, Tlen, _, _) ->
    yystate(50, Ics, Line, Tlen+1, 2, Tlen);
yystate(77, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(37, Ics, Line, Tlen+1, 2, Tlen);
yystate(77, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 77 ->
    yystate(37, Ics, Line, Tlen+1, 2, Tlen);
yystate(77, [C|Ics], Line, Tlen, _, _) when C >= 79, C =< 90 ->
    yystate(37, Ics, Line, Tlen+1, 2, Tlen);
yystate(77, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(37, Ics, Line, Tlen+1, 2, Tlen);
yystate(77, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line,77};
yystate(76, Ics, Line, Tlen, _, _) ->
    {28,Tlen,Ics,Line};
yystate(75, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(75, Ics, Line, Tlen+1, 5, Tlen);
yystate(75, Ics, Line, Tlen, _, _) ->
    {5,Tlen,Ics,Line,75};
yystate(74, [95|Ics], Line, Tlen, _, _) ->
    yystate(37, Ics, Line, Tlen+1, 2, Tlen);
yystate(74, [79|Ics], Line, Tlen, _, _) ->
    yystate(52, Ics, Line, Tlen+1, 2, Tlen);
yystate(74, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(37, Ics, Line, Tlen+1, 2, Tlen);
yystate(74, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 78 ->
    yystate(37, Ics, Line, Tlen+1, 2, Tlen);
yystate(74, [C|Ics], Line, Tlen, _, _) when C >= 80, C =< 90 ->
    yystate(37, Ics, Line, Tlen+1, 2, Tlen);
yystate(74, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(37, Ics, Line, Tlen+1, 2, Tlen);
yystate(74, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line,74};
yystate(73, [94|Ics], Line, Tlen, Action, Alen) ->
    yystate(73, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(23, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(54, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(23, Ics, Line+1, Tlen+1, Action, Alen);
yystate(73, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(23, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(23, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 45 ->
    yystate(23, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [C|Ics], Line, Tlen, Action, Alen) when C >= 47, C =< 93 ->
    yystate(23, Ics, Line, Tlen+1, Action, Alen);
yystate(73, [C|Ics], Line, Tlen, Action, Alen) when C >= 95 ->
    yystate(23, Ics, Line, Tlen+1, Action, Alen);
yystate(73, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,73};
yystate(72, Ics, Line, Tlen, _, _) ->
    {34,Tlen,Ics,Line};
yystate(71, [113|Ics], Line, Tlen, _, _) ->
    yystate(30, Ics, Line, Tlen+1, 1, Tlen);
yystate(71, [95|Ics], Line, Tlen, _, _) ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(71, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(71, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(71, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 112 ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(71, [C|Ics], Line, Tlen, _, _) when C >= 114, C =< 122 ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(71, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line,71};
yystate(70, [48|Ics], Line, Tlen, Action, Alen) ->
    yystate(33, Ics, Line, Tlen+1, Action, Alen);
yystate(70, [49|Ics], Line, Tlen, Action, Alen) ->
    yystate(33, Ics, Line, Tlen+1, Action, Alen);
yystate(70, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,70};
yystate(69, Ics, Line, Tlen, _, _) ->
    {12,Tlen,Ics,Line};
yystate(68, Ics, Line, Tlen, _, _) ->
    {52,Tlen,Ics,Line};
yystate(67, Ics, Line, Tlen, _, _) ->
    {35,Tlen,Ics,Line};
yystate(66, [111|Ics], Line, Tlen, _, _) ->
    yystate(29, Ics, Line, Tlen+1, 1, Tlen);
yystate(66, [95|Ics], Line, Tlen, _, _) ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(66, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(66, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(66, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 110 ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(66, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(66, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line,66};
yystate(65, [103|Ics], Line, Tlen, _, _) ->
    yystate(24, Ics, Line, Tlen+1, 1, Tlen);
yystate(65, [95|Ics], Line, Tlen, _, _) ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 102 ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(65, [C|Ics], Line, Tlen, _, _) when C >= 104, C =< 122 ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(65, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line,65};
yystate(64, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(21, Ics, Line, Tlen+1, Action, Alen);
yystate(64, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(21, Ics, Line+1, Tlen+1, Action, Alen);
yystate(64, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(21, Ics, Line, Tlen+1, Action, Alen);
yystate(64, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 38 ->
    yystate(21, Ics, Line, Tlen+1, Action, Alen);
yystate(64, [C|Ics], Line, Tlen, Action, Alen) when C >= 40 ->
    yystate(21, Ics, Line, Tlen+1, Action, Alen);
yystate(64, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,64};
yystate(63, [61|Ics], Line, Tlen, _, _) ->
    yystate(48, Ics, Line, Tlen+1, 46, Tlen);
yystate(63, [60|Ics], Line, Tlen, _, _) ->
    yystate(3, Ics, Line, Tlen+1, 46, Tlen);
yystate(63, [45|Ics], Line, Tlen, _, _) ->
    yystate(26, Ics, Line, Tlen+1, 46, Tlen);
yystate(63, Ics, Line, Tlen, _, _) ->
    {46,Tlen,Ics,Line,63};
yystate(62, [105|Ics], Line, Tlen, _, _) ->
    yystate(65, Ics, Line, Tlen+1, 1, Tlen);
yystate(62, [95|Ics], Line, Tlen, _, _) ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 104 ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(62, [C|Ics], Line, Tlen, _, _) when C >= 106, C =< 122 ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(62, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line,62};
yystate(61, Ics, Line, Tlen, _, _) ->
    {57,Tlen,Ics,Line};
yystate(60, [61|Ics], Line, Tlen, _, _) ->
    yystate(59, Ics, Line, Tlen+1, 24, Tlen);
yystate(60, Ics, Line, Tlen, _, _) ->
    {24,Tlen,Ics,Line,60};
yystate(59, Ics, Line, Tlen, _, _) ->
    {45,Tlen,Ics,Line};
yystate(58, [38|Ics], Line, Tlen, _, _) ->
    yystate(69, Ics, Line, Tlen+1, 13, Tlen);
yystate(58, Ics, Line, Tlen, _, _) ->
    {13,Tlen,Ics,Line,58};
yystate(57, [120|Ics], Line, Tlen, _, _) ->
    yystate(7, Ics, Line, Tlen+1, 6, Tlen);
yystate(57, [98|Ics], Line, Tlen, _, _) ->
    yystate(70, Ics, Line, Tlen+1, 6, Tlen);
yystate(57, [88|Ics], Line, Tlen, _, _) ->
    yystate(7, Ics, Line, Tlen+1, 6, Tlen);
yystate(57, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(75, Ics, Line, Tlen+1, 6, Tlen);
yystate(57, Ics, Line, Tlen, _, _) ->
    {6,Tlen,Ics,Line,57};
yystate(56, [112|Ics], Line, Tlen, _, _) ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(56, [95|Ics], Line, Tlen, _, _) ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 111 ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(56, [C|Ics], Line, Tlen, _, _) when C >= 113, C =< 122 ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(56, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line,56};
yystate(55, Ics, Line, Tlen, _, _) ->
    {44,Tlen,Ics,Line};
yystate(54, [94|Ics], Line, Tlen, _, _) ->
    yystate(73, Ics, Line, Tlen+1, 0, Tlen);
yystate(54, [46|Ics], Line, Tlen, _, _) ->
    yystate(23, Ics, Line, Tlen+1, 0, Tlen);
yystate(54, [34|Ics], Line, Tlen, _, _) ->
    yystate(17, Ics, Line, Tlen+1, 0, Tlen);
yystate(54, [10|Ics], Line, Tlen, _, _) ->
    yystate(23, Ics, Line+1, Tlen+1, 0, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(23, Ics, Line, Tlen+1, 0, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 33 ->
    yystate(23, Ics, Line, Tlen+1, 0, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 35, C =< 45 ->
    yystate(23, Ics, Line, Tlen+1, 0, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 47, C =< 93 ->
    yystate(23, Ics, Line, Tlen+1, 0, Tlen);
yystate(54, [C|Ics], Line, Tlen, _, _) when C >= 95 ->
    yystate(23, Ics, Line, Tlen+1, 0, Tlen);
yystate(54, Ics, Line, Tlen, _, _) ->
    {0,Tlen,Ics,Line,54};
yystate(53, Ics, Line, Tlen, _, _) ->
    {55,Tlen,Ics,Line};
yystate(52, [95|Ics], Line, Tlen, _, _) ->
    yystate(37, Ics, Line, Tlen+1, 2, Tlen);
yystate(52, [82|Ics], Line, Tlen, _, _) ->
    yystate(37, Ics, Line, Tlen+1, 2, Tlen);
yystate(52, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(37, Ics, Line, Tlen+1, 2, Tlen);
yystate(52, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 81 ->
    yystate(37, Ics, Line, Tlen+1, 2, Tlen);
yystate(52, [C|Ics], Line, Tlen, _, _) when C >= 83, C =< 90 ->
    yystate(37, Ics, Line, Tlen+1, 2, Tlen);
yystate(52, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(37, Ics, Line, Tlen+1, 2, Tlen);
yystate(52, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line,52};
yystate(51, Ics, Line, Tlen, _, _) ->
    {48,Tlen,Ics,Line};
yystate(50, [95|Ics], Line, Tlen, _, _) ->
    yystate(37, Ics, Line, Tlen+1, 2, Tlen);
yystate(50, [68|Ics], Line, Tlen, _, _) ->
    yystate(37, Ics, Line, Tlen+1, 2, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(37, Ics, Line, Tlen+1, 2, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 67 ->
    yystate(37, Ics, Line, Tlen+1, 2, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 69, C =< 90 ->
    yystate(37, Ics, Line, Tlen+1, 2, Tlen);
yystate(50, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(37, Ics, Line, Tlen+1, 2, Tlen);
yystate(50, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line,50};
yystate(49, [95|Ics], Line, Tlen, _, _) ->
    yystate(37, Ics, Line, Tlen+1, 2, Tlen);
yystate(49, [80|Ics], Line, Tlen, _, _) ->
    yystate(37, Ics, Line, Tlen+1, 2, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(37, Ics, Line, Tlen+1, 2, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 79 ->
    yystate(37, Ics, Line, Tlen+1, 2, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 81, C =< 90 ->
    yystate(37, Ics, Line, Tlen+1, 2, Tlen);
yystate(49, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(37, Ics, Line, Tlen+1, 2, Tlen);
yystate(49, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line,49};
yystate(48, Ics, Line, Tlen, _, _) ->
    {43,Tlen,Ics,Line};
yystate(47, Ics, Line, Tlen, _, _) ->
    {53,Tlen,Ics,Line};
yystate(46, Ics, Line, Tlen, _, _) ->
    {17,Tlen,Ics,Line};
yystate(45, [126|Ics], Line, Tlen, Action, Alen) ->
    yystate(4, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [125|Ics], Line, Tlen, Action, Alen) ->
    yystate(40, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [124|Ics], Line, Tlen, Action, Alen) ->
    yystate(81, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [123|Ics], Line, Tlen, Action, Alen) ->
    yystate(9, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [121|Ics], Line, Tlen, Action, Alen) ->
    yystate(35, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [122|Ics], Line, Tlen, Action, Alen) ->
    yystate(35, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [120|Ics], Line, Tlen, Action, Alen) ->
    yystate(31, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [118|Ics], Line, Tlen, Action, Alen) ->
    yystate(35, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [119|Ics], Line, Tlen, Action, Alen) ->
    yystate(35, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [117|Ics], Line, Tlen, Action, Alen) ->
    yystate(5, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [116|Ics], Line, Tlen, Action, Alen) ->
    yystate(35, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [115|Ics], Line, Tlen, Action, Alen) ->
    yystate(62, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [111|Ics], Line, Tlen, Action, Alen) ->
    yystate(80, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [110|Ics], Line, Tlen, Action, Alen) ->
    yystate(66, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [105|Ics], Line, Tlen, Action, Alen) ->
    yystate(11, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [101|Ics], Line, Tlen, Action, Alen) ->
    yystate(71, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [97|Ics], Line, Tlen, Action, Alen) ->
    yystate(6, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [94|Ics], Line, Tlen, Action, Alen) ->
    yystate(32, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [93|Ics], Line, Tlen, Action, Alen) ->
    yystate(12, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [91|Ics], Line, Tlen, Action, Alen) ->
    yystate(53, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [89|Ics], Line, Tlen, Action, Alen) ->
    yystate(37, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [90|Ics], Line, Tlen, Action, Alen) ->
    yystate(37, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [88|Ics], Line, Tlen, Action, Alen) ->
    yystate(74, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [79|Ics], Line, Tlen, Action, Alen) ->
    yystate(52, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [78|Ics], Line, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [73|Ics], Line, Tlen, Action, Alen) ->
    yystate(78, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [69|Ics], Line, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [65|Ics], Line, Tlen, Action, Alen) ->
    yystate(77, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [62|Ics], Line, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [61|Ics], Line, Tlen, Action, Alen) ->
    yystate(14, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [60|Ics], Line, Tlen, Action, Alen) ->
    yystate(63, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [59|Ics], Line, Tlen, Action, Alen) ->
    yystate(51, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [58|Ics], Line, Tlen, Action, Alen) ->
    yystate(68, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [48|Ics], Line, Tlen, Action, Alen) ->
    yystate(57, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [47|Ics], Line, Tlen, Action, Alen) ->
    yystate(34, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(2, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [45|Ics], Line, Tlen, Action, Alen) ->
    yystate(43, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [44|Ics], Line, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [43|Ics], Line, Tlen, Action, Alen) ->
    yystate(1, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [42|Ics], Line, Tlen, Action, Alen) ->
    yystate(38, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [41|Ics], Line, Tlen, Action, Alen) ->
    yystate(25, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [40|Ics], Line, Tlen, Action, Alen) ->
    yystate(47, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(64, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [38|Ics], Line, Tlen, Action, Alen) ->
    yystate(58, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [37|Ics], Line, Tlen, Action, Alen) ->
    yystate(28, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [35|Ics], Line, Tlen, Action, Alen) ->
    yystate(16, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(23, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [33|Ics], Line, Tlen, Action, Alen) ->
    yystate(60, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(18, Ics, Line+1, Tlen+1, Action, Alen);
yystate(45, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(18, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 32 ->
    yystate(18, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [C|Ics], Line, Tlen, Action, Alen) when C >= 49, C =< 57 ->
    yystate(15, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [C|Ics], Line, Tlen, Action, Alen) when C >= 66, C =< 68 ->
    yystate(37, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [C|Ics], Line, Tlen, Action, Alen) when C >= 70, C =< 72 ->
    yystate(37, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [C|Ics], Line, Tlen, Action, Alen) when C >= 74, C =< 77 ->
    yystate(37, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [C|Ics], Line, Tlen, Action, Alen) when C >= 80, C =< 87 ->
    yystate(37, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [C|Ics], Line, Tlen, Action, Alen) when C >= 98, C =< 100 ->
    yystate(35, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [C|Ics], Line, Tlen, Action, Alen) when C >= 102, C =< 104 ->
    yystate(35, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [C|Ics], Line, Tlen, Action, Alen) when C >= 106, C =< 109 ->
    yystate(35, Ics, Line, Tlen+1, Action, Alen);
yystate(45, [C|Ics], Line, Tlen, Action, Alen) when C >= 112, C =< 114 ->
    yystate(35, Ics, Line, Tlen+1, Action, Alen);
yystate(45, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,45};
yystate(44, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(44, Ics, Line, Tlen+1, 3, Tlen);
yystate(44, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 70 ->
    yystate(44, Ics, Line, Tlen+1, 3, Tlen);
yystate(44, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 102 ->
    yystate(44, Ics, Line, Tlen+1, 3, Tlen);
yystate(44, Ics, Line, Tlen, _, _) ->
    {3,Tlen,Ics,Line,44};
yystate(43, [62|Ics], Line, Tlen, _, _) ->
    yystate(76, Ics, Line, Tlen+1, 39, Tlen);
yystate(43, Ics, Line, Tlen, _, _) ->
    {39,Tlen,Ics,Line,43};
yystate(42, [115|Ics], Line, Tlen, _, _) ->
    yystate(62, Ics, Line, Tlen+1, 1, Tlen);
yystate(42, [95|Ics], Line, Tlen, _, _) ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 114 ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(42, [C|Ics], Line, Tlen, _, _) when C >= 116, C =< 122 ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(42, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line,42};
yystate(41, [95|Ics], Line, Tlen, _, _) ->
    yystate(37, Ics, Line, Tlen+1, 2, Tlen);
yystate(41, [84|Ics], Line, Tlen, _, _) ->
    yystate(37, Ics, Line, Tlen+1, 2, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(37, Ics, Line, Tlen+1, 2, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 83 ->
    yystate(37, Ics, Line, Tlen+1, 2, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 85, C =< 90 ->
    yystate(37, Ics, Line, Tlen+1, 2, Tlen);
yystate(41, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(37, Ics, Line, Tlen+1, 2, Tlen);
yystate(41, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line,41};
yystate(40, Ics, Line, Tlen, _, _) ->
    {50,Tlen,Ics,Line};
yystate(39, Ics, Line, Tlen, _, _) ->
    {51,Tlen,Ics,Line};
yystate(38, Ics, Line, Tlen, _, _) ->
    {40,Tlen,Ics,Line};
yystate(37, [95|Ics], Line, Tlen, _, _) ->
    yystate(37, Ics, Line, Tlen+1, 2, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(37, Ics, Line, Tlen+1, 2, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(37, Ics, Line, Tlen+1, 2, Tlen);
yystate(37, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(37, Ics, Line, Tlen+1, 2, Tlen);
yystate(37, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line,37};
yystate(36, [95|Ics], Line, Tlen, _, _) ->
    yystate(37, Ics, Line, Tlen+1, 2, Tlen);
yystate(36, [85|Ics], Line, Tlen, _, _) ->
    yystate(37, Ics, Line, Tlen+1, 2, Tlen);
yystate(36, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(37, Ics, Line, Tlen+1, 2, Tlen);
yystate(36, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 84 ->
    yystate(37, Ics, Line, Tlen+1, 2, Tlen);
yystate(36, [C|Ics], Line, Tlen, _, _) when C >= 86, C =< 90 ->
    yystate(37, Ics, Line, Tlen+1, 2, Tlen);
yystate(36, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(37, Ics, Line, Tlen+1, 2, Tlen);
yystate(36, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line,36};
yystate(35, [95|Ics], Line, Tlen, _, _) ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(35, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(35, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line,35};
yystate(34, Ics, Line, Tlen, _, _) ->
    {41,Tlen,Ics,Line};
yystate(33, [48|Ics], Line, Tlen, _, _) ->
    yystate(33, Ics, Line, Tlen+1, 4, Tlen);
yystate(33, [49|Ics], Line, Tlen, _, _) ->
    yystate(33, Ics, Line, Tlen+1, 4, Tlen);
yystate(33, Ics, Line, Tlen, _, _) ->
    {4,Tlen,Ics,Line,33};
yystate(32, Ics, Line, Tlen, _, _) ->
    {21,Tlen,Ics,Line};
yystate(31, [111|Ics], Line, Tlen, _, _) ->
    yystate(80, Ics, Line, Tlen+1, 1, Tlen);
yystate(31, [95|Ics], Line, Tlen, _, _) ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(31, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(31, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(31, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 110 ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(31, [C|Ics], Line, Tlen, _, _) when C >= 112, C =< 122 ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(31, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line,31};
yystate(30, [117|Ics], Line, Tlen, _, _) ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(30, [95|Ics], Line, Tlen, _, _) ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 116 ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(30, [C|Ics], Line, Tlen, _, _) when C >= 118, C =< 122 ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(30, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line,30};
yystate(29, [116|Ics], Line, Tlen, _, _) ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(29, [95|Ics], Line, Tlen, _, _) ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 115 ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(29, [C|Ics], Line, Tlen, _, _) when C >= 117, C =< 122 ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(29, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line,29};
yystate(28, Ics, Line, Tlen, _, _) ->
    {42,Tlen,Ics,Line};
yystate(27, [62|Ics], Line, Tlen, _, _) ->
    yystate(72, Ics, Line, Tlen+1, 36, Tlen);
yystate(27, Ics, Line, Tlen, _, _) ->
    {36,Tlen,Ics,Line,27};
yystate(26, [62|Ics], Line, Tlen, Action, Alen) ->
    yystate(10, Ics, Line, Tlen+1, Action, Alen);
yystate(26, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,26};
yystate(25, Ics, Line, Tlen, _, _) ->
    {54,Tlen,Ics,Line};
yystate(24, [110|Ics], Line, Tlen, _, _) ->
    yystate(20, Ics, Line, Tlen+1, 1, Tlen);
yystate(24, [95|Ics], Line, Tlen, _, _) ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(24, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(24, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line,24};
yystate(23, [94|Ics], Line, Tlen, Action, Alen) ->
    yystate(73, Ics, Line, Tlen+1, Action, Alen);
yystate(23, [46|Ics], Line, Tlen, Action, Alen) ->
    yystate(23, Ics, Line, Tlen+1, Action, Alen);
yystate(23, [34|Ics], Line, Tlen, Action, Alen) ->
    yystate(17, Ics, Line, Tlen+1, Action, Alen);
yystate(23, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(23, Ics, Line+1, Tlen+1, Action, Alen);
yystate(23, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(23, Ics, Line, Tlen+1, Action, Alen);
yystate(23, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 33 ->
    yystate(23, Ics, Line, Tlen+1, Action, Alen);
yystate(23, [C|Ics], Line, Tlen, Action, Alen) when C >= 35, C =< 45 ->
    yystate(23, Ics, Line, Tlen+1, Action, Alen);
yystate(23, [C|Ics], Line, Tlen, Action, Alen) when C >= 47, C =< 93 ->
    yystate(23, Ics, Line, Tlen+1, Action, Alen);
yystate(23, [C|Ics], Line, Tlen, Action, Alen) when C >= 95 ->
    yystate(23, Ics, Line, Tlen+1, Action, Alen);
yystate(23, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,23};
yystate(22, Ics, Line, Tlen, _, _) ->
    {32,Tlen,Ics,Line};
yystate(21, [39|Ics], Line, Tlen, Action, Alen) ->
    yystate(19, Ics, Line, Tlen+1, Action, Alen);
yystate(21, [10|Ics], Line, Tlen, Action, Alen) ->
    yystate(21, Ics, Line+1, Tlen+1, Action, Alen);
yystate(21, [C|Ics], Line, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(21, Ics, Line, Tlen+1, Action, Alen);
yystate(21, [C|Ics], Line, Tlen, Action, Alen) when C >= 11, C =< 38 ->
    yystate(21, Ics, Line, Tlen+1, Action, Alen);
yystate(21, [C|Ics], Line, Tlen, Action, Alen) when C >= 40 ->
    yystate(21, Ics, Line, Tlen+1, Action, Alen);
yystate(21, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,21};
yystate(20, [101|Ics], Line, Tlen, _, _) ->
    yystate(79, Ics, Line, Tlen+1, 1, Tlen);
yystate(20, [95|Ics], Line, Tlen, _, _) ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(20, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(20, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(20, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 100 ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(20, [C|Ics], Line, Tlen, _, _) when C >= 102, C =< 122 ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(20, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line,20};
yystate(19, [39|Ics], Line, Tlen, _, _) ->
    yystate(19, Ics, Line, Tlen+1, 7, Tlen);
yystate(19, [10|Ics], Line, Tlen, _, _) ->
    yystate(21, Ics, Line+1, Tlen+1, 7, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(21, Ics, Line, Tlen+1, 7, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 38 ->
    yystate(21, Ics, Line, Tlen+1, 7, Tlen);
yystate(19, [C|Ics], Line, Tlen, _, _) when C >= 40 ->
    yystate(21, Ics, Line, Tlen+1, 7, Tlen);
yystate(19, Ics, Line, Tlen, _, _) ->
    {7,Tlen,Ics,Line,19};
yystate(18, [10|Ics], Line, Tlen, _, _) ->
    yystate(18, Ics, Line+1, Tlen+1, 59, Tlen);
yystate(18, [C|Ics], Line, Tlen, _, _) when C >= 0, C =< 9 ->
    yystate(18, Ics, Line, Tlen+1, 59, Tlen);
yystate(18, [C|Ics], Line, Tlen, _, _) when C >= 11, C =< 32 ->
    yystate(18, Ics, Line, Tlen+1, 59, Tlen);
yystate(18, Ics, Line, Tlen, _, _) ->
    {59,Tlen,Ics,Line,18};
yystate(17, Ics, Line, Tlen, _, _) ->
    {0,Tlen,Ics,Line};
yystate(16, Ics, Line, Tlen, _, _) ->
    {16,Tlen,Ics,Line};
yystate(15, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(15, Ics, Line, Tlen+1, 6, Tlen);
yystate(15, Ics, Line, Tlen, _, _) ->
    {6,Tlen,Ics,Line,15};
yystate(14, [61|Ics], Line, Tlen, _, _) ->
    yystate(22, Ics, Line, Tlen+1, 33, Tlen);
yystate(14, Ics, Line, Tlen, _, _) ->
    {33,Tlen,Ics,Line,14};
yystate(13, [62|Ics], Line, Tlen, _, _) ->
    yystate(27, Ics, Line, Tlen+1, 47, Tlen);
yystate(13, [61|Ics], Line, Tlen, _, _) ->
    yystate(55, Ics, Line, Tlen+1, 47, Tlen);
yystate(13, Ics, Line, Tlen, _, _) ->
    {47,Tlen,Ics,Line,13};
yystate(12, Ics, Line, Tlen, _, _) ->
    {56,Tlen,Ics,Line};
yystate(11, [109|Ics], Line, Tlen, _, _) ->
    yystate(56, Ics, Line, Tlen+1, 1, Tlen);
yystate(11, [95|Ics], Line, Tlen, _, _) ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 108 ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(11, [C|Ics], Line, Tlen, _, _) when C >= 110, C =< 122 ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(11, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line,11};
yystate(10, Ics, Line, Tlen, _, _) ->
    {31,Tlen,Ics,Line};
yystate(9, Ics, Line, Tlen, _, _) ->
    {49,Tlen,Ics,Line};
yystate(8, [95|Ics], Line, Tlen, _, _) ->
    yystate(37, Ics, Line, Tlen+1, 2, Tlen);
yystate(8, [81|Ics], Line, Tlen, _, _) ->
    yystate(36, Ics, Line, Tlen+1, 2, Tlen);
yystate(8, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(37, Ics, Line, Tlen+1, 2, Tlen);
yystate(8, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 80 ->
    yystate(37, Ics, Line, Tlen+1, 2, Tlen);
yystate(8, [C|Ics], Line, Tlen, _, _) when C >= 82, C =< 90 ->
    yystate(37, Ics, Line, Tlen+1, 2, Tlen);
yystate(8, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(37, Ics, Line, Tlen+1, 2, Tlen);
yystate(8, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line,8};
yystate(7, [C|Ics], Line, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(44, Ics, Line, Tlen+1, Action, Alen);
yystate(7, [C|Ics], Line, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(44, Ics, Line, Tlen+1, Action, Alen);
yystate(7, [C|Ics], Line, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(44, Ics, Line, Tlen+1, Action, Alen);
yystate(7, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,7};
yystate(6, [110|Ics], Line, Tlen, _, _) ->
    yystate(79, Ics, Line, Tlen+1, 1, Tlen);
yystate(6, [95|Ics], Line, Tlen, _, _) ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(6, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(6, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line,6};
yystate(5, [110|Ics], Line, Tlen, _, _) ->
    yystate(42, Ics, Line, Tlen+1, 1, Tlen);
yystate(5, [95|Ics], Line, Tlen, _, _) ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 90 ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 109 ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(5, [C|Ics], Line, Tlen, _, _) when C >= 111, C =< 122 ->
    yystate(35, Ics, Line, Tlen+1, 1, Tlen);
yystate(5, Ics, Line, Tlen, _, _) ->
    {1,Tlen,Ics,Line,5};
yystate(4, Ics, Line, Tlen, _, _) ->
    {25,Tlen,Ics,Line};
yystate(3, [60|Ics], Line, Tlen, _, _) ->
    yystate(67, Ics, Line, Tlen+1, 37, Tlen);
yystate(3, Ics, Line, Tlen, _, _) ->
    {37,Tlen,Ics,Line,3};
yystate(2, [46|Ics], Line, Tlen, _, _) ->
    yystate(61, Ics, Line, Tlen+1, 58, Tlen);
yystate(2, Ics, Line, Tlen, _, _) ->
    {58,Tlen,Ics,Line,2};
yystate(1, Ics, Line, Tlen, _, _) ->
    {38,Tlen,Ics,Line};
yystate(0, [95|Ics], Line, Tlen, _, _) ->
    yystate(37, Ics, Line, Tlen+1, 2, Tlen);
yystate(0, [79|Ics], Line, Tlen, _, _) ->
    yystate(41, Ics, Line, Tlen+1, 2, Tlen);
yystate(0, [C|Ics], Line, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(37, Ics, Line, Tlen+1, 2, Tlen);
yystate(0, [C|Ics], Line, Tlen, _, _) when C >= 65, C =< 78 ->
    yystate(37, Ics, Line, Tlen+1, 2, Tlen);
yystate(0, [C|Ics], Line, Tlen, _, _) when C >= 80, C =< 90 ->
    yystate(37, Ics, Line, Tlen+1, 2, Tlen);
yystate(0, [C|Ics], Line, Tlen, _, _) when C >= 97, C =< 122 ->
    yystate(37, Ics, Line, Tlen+1, 2, Tlen);
yystate(0, Ics, Line, Tlen, _, _) ->
    {2,Tlen,Ics,Line,0};
yystate(S, Ics, Line, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,S}.

%% yyaction(Action, TokenLength, TokenChars, TokenLine) ->
%% {token,Token} | {end_token, Token} | skip_token | {error,String}.
%% Generated action function.

yyaction(0, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_0(TokenChars, TokenLen, TokenLine);
yyaction(1, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_1(TokenChars, TokenLine);
yyaction(2, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_2(TokenChars, TokenLine);
yyaction(3, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_3(TokenChars, TokenLine);
yyaction(4, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_4(TokenChars, TokenLine);
yyaction(5, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_5(TokenChars, TokenLine);
yyaction(6, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_6(TokenChars, TokenLine);
yyaction(7, TokenLen, YYtcs, TokenLine) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_7(TokenChars, TokenLine);
yyaction(8, _, _, TokenLine) ->
    yyaction_8(TokenLine);
yyaction(9, _, _, TokenLine) ->
    yyaction_9(TokenLine);
yyaction(10, _, _, TokenLine) ->
    yyaction_10(TokenLine);
yyaction(11, _, _, TokenLine) ->
    yyaction_11(TokenLine);
yyaction(12, _, _, TokenLine) ->
    yyaction_12(TokenLine);
yyaction(13, _, _, TokenLine) ->
    yyaction_13(TokenLine);
yyaction(14, _, _, TokenLine) ->
    yyaction_14(TokenLine);
yyaction(15, _, _, TokenLine) ->
    yyaction_15(TokenLine);
yyaction(16, _, _, TokenLine) ->
    yyaction_16(TokenLine);
yyaction(17, _, _, TokenLine) ->
    yyaction_17(TokenLine);
yyaction(18, _, _, TokenLine) ->
    yyaction_18(TokenLine);
yyaction(19, _, _, TokenLine) ->
    yyaction_19(TokenLine);
yyaction(20, _, _, TokenLine) ->
    yyaction_20(TokenLine);
yyaction(21, _, _, TokenLine) ->
    yyaction_21(TokenLine);
yyaction(22, _, _, TokenLine) ->
    yyaction_22(TokenLine);
yyaction(23, _, _, TokenLine) ->
    yyaction_23(TokenLine);
yyaction(24, _, _, TokenLine) ->
    yyaction_24(TokenLine);
yyaction(25, _, _, TokenLine) ->
    yyaction_25(TokenLine);
yyaction(26, _, _, TokenLine) ->
    yyaction_26(TokenLine);
yyaction(27, _, _, TokenLine) ->
    yyaction_27(TokenLine);
yyaction(28, _, _, TokenLine) ->
    yyaction_28(TokenLine);
yyaction(29, _, _, TokenLine) ->
    yyaction_29(TokenLine);
yyaction(30, _, _, TokenLine) ->
    yyaction_30(TokenLine);
yyaction(31, _, _, TokenLine) ->
    yyaction_31(TokenLine);
yyaction(32, _, _, TokenLine) ->
    yyaction_32(TokenLine);
yyaction(33, _, _, TokenLine) ->
    yyaction_33(TokenLine);
yyaction(34, _, _, TokenLine) ->
    yyaction_34(TokenLine);
yyaction(35, _, _, TokenLine) ->
    yyaction_35(TokenLine);
yyaction(36, _, _, TokenLine) ->
    yyaction_36(TokenLine);
yyaction(37, _, _, TokenLine) ->
    yyaction_37(TokenLine);
yyaction(38, _, _, TokenLine) ->
    yyaction_38(TokenLine);
yyaction(39, _, _, TokenLine) ->
    yyaction_39(TokenLine);
yyaction(40, _, _, TokenLine) ->
    yyaction_40(TokenLine);
yyaction(41, _, _, TokenLine) ->
    yyaction_41(TokenLine);
yyaction(42, _, _, TokenLine) ->
    yyaction_42(TokenLine);
yyaction(43, _, _, TokenLine) ->
    yyaction_43(TokenLine);
yyaction(44, _, _, TokenLine) ->
    yyaction_44(TokenLine);
yyaction(45, _, _, TokenLine) ->
    yyaction_45(TokenLine);
yyaction(46, _, _, TokenLine) ->
    yyaction_46(TokenLine);
yyaction(47, _, _, TokenLine) ->
    yyaction_47(TokenLine);
yyaction(48, _, _, TokenLine) ->
    yyaction_48(TokenLine);
yyaction(49, _, _, TokenLine) ->
    yyaction_49(TokenLine);
yyaction(50, _, _, TokenLine) ->
    yyaction_50(TokenLine);
yyaction(51, _, _, TokenLine) ->
    yyaction_51(TokenLine);
yyaction(52, _, _, TokenLine) ->
    yyaction_52(TokenLine);
yyaction(53, _, _, TokenLine) ->
    yyaction_53(TokenLine);
yyaction(54, _, _, TokenLine) ->
    yyaction_54(TokenLine);
yyaction(55, _, _, TokenLine) ->
    yyaction_55(TokenLine);
yyaction(56, _, _, TokenLine) ->
    yyaction_56(TokenLine);
yyaction(57, _, _, TokenLine) ->
    yyaction_57(TokenLine);
yyaction(58, _, _, TokenLine) ->
    yyaction_58(TokenLine);
yyaction(59, _, _, _) ->
    yyaction_59();
yyaction(_, _, _, _) -> error.

-compile({inline,yyaction_0/3}).
-file("./varp_scan.xrl", 17).
yyaction_0(TokenChars, TokenLen, TokenLine) ->
     begin
     S = lists : sublist (TokenChars, 2, TokenLen - 2),
     { token, { string, TokenLine, S } }
     end .

-compile({inline,yyaction_1/2}).
-file("./varp_scan.xrl", 21).
yyaction_1(TokenChars, TokenLine) ->
     { token, { variable, TokenLine, TokenChars } } .

-compile({inline,yyaction_2/2}).
-file("./varp_scan.xrl", 22).
yyaction_2(TokenChars, TokenLine) ->
     { token, { symbol, TokenLine, TokenChars } } .

-compile({inline,yyaction_3/2}).
-file("./varp_scan.xrl", 24).
yyaction_3(TokenChars, TokenLine) ->
     { token, { hexnum, TokenLine, TokenChars } } .

-compile({inline,yyaction_4/2}).
-file("./varp_scan.xrl", 25).
yyaction_4(TokenChars, TokenLine) ->
     { token, { binnum, TokenLine, TokenChars } } .

-compile({inline,yyaction_5/2}).
-file("./varp_scan.xrl", 26).
yyaction_5(TokenChars, TokenLine) ->
     { token, { octnum, TokenLine, TokenChars } } .

-compile({inline,yyaction_6/2}).
-file("./varp_scan.xrl", 27).
yyaction_6(TokenChars, TokenLine) ->
     { token, { decnum, TokenLine, TokenChars } } .

-compile({inline,yyaction_7/2}).
-file("./varp_scan.xrl", 29).
yyaction_7(TokenChars, TokenLine) ->
     { token, { chrnum, TokenLine, TokenChars } } .

-compile({inline,yyaction_8/1}).
-file("./varp_scan.xrl", 36).
yyaction_8(TokenLine) ->
     { token, { unsigned, TokenLine } } .

-compile({inline,yyaction_9/1}).
-file("./varp_scan.xrl", 37).
yyaction_9(TokenLine) ->
     { token, { signed, TokenLine } } .

-compile({inline,yyaction_10/1}).
-file("./varp_scan.xrl", 41).
yyaction_10(TokenLine) ->
     { token, { 'and', TokenLine } } .

-compile({inline,yyaction_11/1}).
-file("./varp_scan.xrl", 42).
yyaction_11(TokenLine) ->
     { token, { 'and', TokenLine } } .

-compile({inline,yyaction_12/1}).
-file("./varp_scan.xrl", 43).
yyaction_12(TokenLine) ->
     { token, { '&&', TokenLine } } .

-compile({inline,yyaction_13/1}).
-file("./varp_scan.xrl", 44).
yyaction_13(TokenLine) ->
     { token, { '&', TokenLine } } .

-compile({inline,yyaction_14/1}).
-file("./varp_scan.xrl", 45).
yyaction_14(TokenLine) ->
     { token, { 'or', TokenLine } } .

-compile({inline,yyaction_15/1}).
-file("./varp_scan.xrl", 46).
yyaction_15(TokenLine) ->
     { token, { 'or', TokenLine } } .

-compile({inline,yyaction_16/1}).
-file("./varp_scan.xrl", 47).
yyaction_16(TokenLine) ->
     { token, { '#', TokenLine } } .

-compile({inline,yyaction_17/1}).
-file("./varp_scan.xrl", 48).
yyaction_17(TokenLine) ->
     { token, { '||', TokenLine } } .

-compile({inline,yyaction_18/1}).
-file("./varp_scan.xrl", 49).
yyaction_18(TokenLine) ->
     { token, { '|', TokenLine } } .

-compile({inline,yyaction_19/1}).
-file("./varp_scan.xrl", 50).
yyaction_19(TokenLine) ->
     { token, { 'xor', TokenLine } } .

-compile({inline,yyaction_20/1}).
-file("./varp_scan.xrl", 51).
yyaction_20(TokenLine) ->
     { token, { 'xor', TokenLine } } .

-compile({inline,yyaction_21/1}).
-file("./varp_scan.xrl", 52).
yyaction_21(TokenLine) ->
     { token, { '^', TokenLine } } .

-compile({inline,yyaction_22/1}).
-file("./varp_scan.xrl", 53).
yyaction_22(TokenLine) ->
     { token, { 'not', TokenLine } } .

-compile({inline,yyaction_23/1}).
-file("./varp_scan.xrl", 54).
yyaction_23(TokenLine) ->
     { token, { 'not', TokenLine } } .

-compile({inline,yyaction_24/1}).
-file("./varp_scan.xrl", 55).
yyaction_24(TokenLine) ->
     { token, { '!', TokenLine } } .

-compile({inline,yyaction_25/1}).
-file("./varp_scan.xrl", 56).
yyaction_25(TokenLine) ->
     { token, { '~', TokenLine } } .

-compile({inline,yyaction_26/1}).
-file("./varp_scan.xrl", 57).
yyaction_26(TokenLine) ->
     { token, { imp, TokenLine } } .

-compile({inline,yyaction_27/1}).
-file("./varp_scan.xrl", 58).
yyaction_27(TokenLine) ->
     { token, { imp, TokenLine } } .

-compile({inline,yyaction_28/1}).
-file("./varp_scan.xrl", 59).
yyaction_28(TokenLine) ->
     { token, { '->', TokenLine } } .

-compile({inline,yyaction_29/1}).
-file("./varp_scan.xrl", 60).
yyaction_29(TokenLine) ->
     { token, { equ, TokenLine } } .

-compile({inline,yyaction_30/1}).
-file("./varp_scan.xrl", 61).
yyaction_30(TokenLine) ->
     { token, { equ, TokenLine } } .

-compile({inline,yyaction_31/1}).
-file("./varp_scan.xrl", 62).
yyaction_31(TokenLine) ->
     { token, { '<->', TokenLine } } .

-compile({inline,yyaction_32/1}).
-file("./varp_scan.xrl", 63).
yyaction_32(TokenLine) ->
     { token, { '==', TokenLine } } .

-compile({inline,yyaction_33/1}).
-file("./varp_scan.xrl", 64).
yyaction_33(TokenLine) ->
     { token, { '=', TokenLine } } .

-compile({inline,yyaction_34/1}).
-file("./varp_scan.xrl", 68).
yyaction_34(TokenLine) ->
     { token, { '>>>', TokenLine } } .

-compile({inline,yyaction_35/1}).
-file("./varp_scan.xrl", 69).
yyaction_35(TokenLine) ->
     { token, { '<<<', TokenLine } } .

-compile({inline,yyaction_36/1}).
-file("./varp_scan.xrl", 70).
yyaction_36(TokenLine) ->
     { token, { '>>', TokenLine } } .

-compile({inline,yyaction_37/1}).
-file("./varp_scan.xrl", 71).
yyaction_37(TokenLine) ->
     { token, { '<<', TokenLine } } .

-compile({inline,yyaction_38/1}).
-file("./varp_scan.xrl", 72).
yyaction_38(TokenLine) ->
     { token, { '+', TokenLine } } .

-compile({inline,yyaction_39/1}).
-file("./varp_scan.xrl", 73).
yyaction_39(TokenLine) ->
     { token, { '-', TokenLine } } .

-compile({inline,yyaction_40/1}).
-file("./varp_scan.xrl", 74).
yyaction_40(TokenLine) ->
     { token, { '*', TokenLine } } .

-compile({inline,yyaction_41/1}).
-file("./varp_scan.xrl", 75).
yyaction_41(TokenLine) ->
     { token, { '/', TokenLine } } .

-compile({inline,yyaction_42/1}).
-file("./varp_scan.xrl", 76).
yyaction_42(TokenLine) ->
     { token, { '%', TokenLine } } .

-compile({inline,yyaction_43/1}).
-file("./varp_scan.xrl", 79).
yyaction_43(TokenLine) ->
     { token, { '<=', TokenLine } } .

-compile({inline,yyaction_44/1}).
-file("./varp_scan.xrl", 80).
yyaction_44(TokenLine) ->
     { token, { '>=', TokenLine } } .

-compile({inline,yyaction_45/1}).
-file("./varp_scan.xrl", 81).
yyaction_45(TokenLine) ->
     { token, { '!=', TokenLine } } .

-compile({inline,yyaction_46/1}).
-file("./varp_scan.xrl", 82).
yyaction_46(TokenLine) ->
     { token, { '<', TokenLine } } .

-compile({inline,yyaction_47/1}).
-file("./varp_scan.xrl", 83).
yyaction_47(TokenLine) ->
     { token, { '>', TokenLine } } .

-compile({inline,yyaction_48/1}).
-file("./varp_scan.xrl", 86).
yyaction_48(TokenLine) ->
     { token, { ';', TokenLine } } .

-compile({inline,yyaction_49/1}).
-file("./varp_scan.xrl", 87).
yyaction_49(TokenLine) ->
     { token, { '{', TokenLine } } .

-compile({inline,yyaction_50/1}).
-file("./varp_scan.xrl", 88).
yyaction_50(TokenLine) ->
     { token, { '}', TokenLine } } .

-compile({inline,yyaction_51/1}).
-file("./varp_scan.xrl", 89).
yyaction_51(TokenLine) ->
     { token, { ',', TokenLine } } .

-compile({inline,yyaction_52/1}).
-file("./varp_scan.xrl", 90).
yyaction_52(TokenLine) ->
     { token, { ':', TokenLine } } .

-compile({inline,yyaction_53/1}).
-file("./varp_scan.xrl", 91).
yyaction_53(TokenLine) ->
     { token, { '(', TokenLine } } .

-compile({inline,yyaction_54/1}).
-file("./varp_scan.xrl", 92).
yyaction_54(TokenLine) ->
     { token, { ')', TokenLine } } .

-compile({inline,yyaction_55/1}).
-file("./varp_scan.xrl", 93).
yyaction_55(TokenLine) ->
     { token, { '[', TokenLine } } .

-compile({inline,yyaction_56/1}).
-file("./varp_scan.xrl", 94).
yyaction_56(TokenLine) ->
     { token, { ']', TokenLine } } .

-compile({inline,yyaction_57/1}).
-file("./varp_scan.xrl", 95).
yyaction_57(TokenLine) ->
     { token, { '..', TokenLine } } .

-compile({inline,yyaction_58/1}).
-file("./varp_scan.xrl", 96).
yyaction_58(TokenLine) ->
     { token, { '.', TokenLine } } .

-compile({inline,yyaction_59/0}).
-file("./varp_scan.xrl", 97).
yyaction_59() ->
     skip_token .

-file("/usr/local/lib/erlang/lib/parsetools-2.0.7/include/leexinc.hrl", 282).
